stages:
  - build

.vars_production: &vars_production
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}

.build:template: &build_definition
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$AUTH"
          }
        }
      }
      EOF
  script:
    - /kaniko/executor
      --cache
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CONTAINER_IMAGE
      --skip-unused-stages
      --target release
      --use-new-run
      --build-arg ENVI=$ENVI
  interruptible: true

# .deploy:template: &deploy_definition
#   stage: deploy
#   image: dtzar/helm-kubectl:3.0.1
#   script:
#     - kubectl set image deployment/kaznet-status-deployment kaznet-status=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

.rules:production:template: &rules_production_definition
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build:production:
  <<: *build_definition
  <<: *rules_production_definition
  variables:
    ENVI: $PRODUCTION_ENVI
    <<: *vars_production

# deploy:production:
#   <<: *deploy_definition
#   <<: *rules_production_definition
#   tags:
#     - deployer
