version: '3.5'

services:
  app:
    container_name: kaznet-status
    image: skeletondocker/kaznet-status:latest
    #image: skeletondocker/kaznet-status:latest_arm64 if ARM Arch needed
    environment:
      TZ: Asia/Almaty
      TELEGRAM_BOT_TOKEN: your-bot-token 
      TELEGRAM_BOT_CHAT_ID: your-chat-id
    restart: unless-stopped

    command: kaznet-status
