apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kaznet-status
  name: kaznet-status
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kaznet-status
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: kaznet-status
    spec:
      containers:
        - args:
            - kaznet-status
          env:
            - name: TELEGRAM_BOT_CHAT_ID
              value: "your-chat-id"
            - name: TELEGRAM_BOT_TOKEN
              value: your-bot-token
            - name: TZ
              value: Asia/Almaty
          image: skeletondocker/kaznet-status:latest
          name: kaznet-status
          resources: {}
      restartPolicy: Always
status: {}
