name: Publish Docker image and deploy staging

on:
  push:
    branches:
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push commit sha for arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GOARCH=arm64
          push: true
          tags: skeletondocker/kaznet-status:staging_arm64_${{ github.sha }}

      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
          command: set image deployment/kaznet-status kaznet-status=skeletondocker/kaznet-status:staging_arm64_${{ github.sha }} --insecure-skip-tls-verify
          
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/kaznet-status
